name: bacon
favicon: null
layout_spectrum: 0.26727
typography_spectrum: 0.004855090752243996
title: bacon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8e0000'
    - '#b52c19'
    - '#d4581d'
    - '#f9a564'
  brandStrength: 0.7636735839769244
  lightness: 0.577524006832391
  saturation: 0.375
  rhythmicContrast: 0.516902789240703
purpose: []
